# Generated by Django 4.0.2 on 2022-02-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='avds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('port', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tittok_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdate', models.CharField(max_length=255)),
                ('number', models.IntegerField(max_length=255)),
            ],
        ),
    ]
