# Generated by Django 4.0.2 on 2022-02-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avds',
            name='port',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tittok_user',
            name='number',
            field=models.IntegerField(),
        ),
    ]
